FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends apt-utils bzip2 build-essential ca-certificates checkinstall cmake curl ffmpeg freeglut3-dev g++ gcc gdb gfortran git htop iputils-ping libatlas-base-dev libavcodec-dev libavformat-dev libblas-dev libccd-dev libcgal-dev libfaac-dev libflann-dev libglew-dev libgphoto2-dev libgtk2.0-dev libhdf5-dev libjpeg8-dev liblapack-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libproj-dev libswscale-dev libtbb-dev libtheora-dev libtiff5-dev libturbojpeg-dev libusb-1.0-0-dev libv4l-dev libvorbis-dev libxine2-dev libxvidcore-dev libyaml-cpp-dev libzmq3-dev net-tools openexr p7zip-full p7zip-rar parallel pkg-config proj-data protobuf-compiler rclone rsync software-properties-common tmux v4l-utils vim wget x264 xvfb yasm zlib1g-dev

SHELL ["/bin/bash", "--login", "-c"]

RUN cd / && wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
    /bin/bash /miniconda.sh -b -p /opt/conda &&\
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh &&\
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc &&\
    /bin/bash -c "source ~/.bashrc" && \
    /opt/conda/bin/conda update -n base -c defaults conda -y &&\
    /opt/conda/bin/conda create -n my python=3.11

ENV PATH /opt/conda/envs/my/bin:$PATH
ENV RCLONE_CONFIG /rclone.conf

RUN conda init bash &&\
    echo "conda activate my" >> ~/.bashrc &&\
    conda activate my &&\
    pip install torch==2.4.0 torchvision==0.19.0 --index-url https://download.pytorch.org/whl/cu124


ENV OPENCV_IO_ENABLE_OPENEXR=1

RUN conda activate my &&\
    pip install scikit-image omegaconf opencv-contrib-python  imgaug Ninja timm albumentations nodejs jupyterlab scipy joblib scikit-learn ruamel.yaml trimesh pyyaml imageio open3d transformations einops gdown  &&\
    pip install -U git+https://github.com/lilohuang/PyTurboJPEG.git &&\
    pip install flash-attn --no-build-isolation &&\
    pip install xformers==0.0.28.post1 --index-url https://download.pytorch.org/whl/cu124 &&\
    pip install onnx onnxruntime-gpu

RUN apt-get update && apt-get install -y \
    libnvinfer10 \
    libnvinfer-plugin10 \
    libnvonnxparsers10

RUN pip3 install onnxruntime-gpu onnx \
    pycuda \
    cuda-python \
    tensorrt

RUN cd / &&  wget https://developer.download.nvidia.com/compute/tensorrt/10.11.0/local_installers/nv-tensorrt-local-repo-ubuntu2004-10.11.0-cuda-12.9_1.0-1_amd64.deb
RUN apt install ./nv-tensorrt-local-repo-ubuntu2004-10.11.0-cuda-12.9_1.0-1_amd64.deb

RUN echo 'alias trtexec="/usr/src/tensorrt/bin/trtexec"' >> ~/.bashrc && source ~/.bashrc

ENV SHELL=/bin/bash
RUN ln -sf /bin/bash /bin/sh


SHELL ["/bin/bash", "-c", "source ~/.bashrc && conda activate my"]
